apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-api-resources
  namespace: rackspace-system
spec:
  project: default
  syncPolicy:
    syncOptions:
    - ServerSideApply=false
    automated:
      selfHeal: true
      prune: false
    retry:
      limit: -1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  source:
    repoURL: 'git@github.com:rackerlabs/rmpk-demo.git'
    targetRevision: HEAD
    path: managed-services/managed-services/gateway
  destination:
    server: "https://kubernetes.default.svc"
    namespace: rackspace-system