apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-api
  namespace: rackspace-system
spec:
  project: default
  syncPolicy:
    syncOptions:
    - ServerSideApply=false
    automated:
      selfHeal: true
      prune: false
    retry:
      limit: -1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  source:
    repoURL: 'git@github.com:rackerlabs/716093-lab1.git'
    targetRevision: main
    path: managed-services/prerequisite/gateway-api
  destination:
    server: "https://kubernetes.default.svc"
    namespace: rackspace-system
