---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: helm-secrets-private-keys
  namespace: rackspace-system
spec:
  encryptedData:
    key.txt: AgDh+gKEQUmbYRLcdFfwqEq3jDvI47VWxnWq9WqU61MY+QIqwMEWm4Hm0OBM+uYxpck4uNXg/Eyr9gXieCvDY+Og7l8ZjRHXs9KBteH6yGLI7Rf6LyFO+OqDrx7OHnfjEdyBtVSGVO2S5ZgCEk57JWWFK4/mnwYBo8S1oj4Nb2JCLyLiamtFZ3SbWeCQdSlbauaLvTK02fffn8onhaBezdOkguSQqLfD8J1JgmiIKCQk3cn4jcLzaz/CSmYCIPxhhPGXSLeMKjTjZoY2CWgs5281oP+7KuPL9C+GRKYFa6kvBDQi7kzgq4D0pDznLE/H56dhSGFbRq77qrV0x2PLOa6ElCWcwI6YCx93mCcr2TarEGYQ5gybBtTw3m7d6Z9HUMU/qtBCTnRXGC/N5ZsZoKr+3Tfva9xPMk/pR4BpVHrsb4tFbBOjeEHfaC2wI+fzSVqIQUc2f7qUMu9VExO1hHtHh5b4ez8lZDWMi4CkMpW2W3ZkKQFeK/R++CfT481+g7TEqNbKXVgWpT94jDpULtj8WIrHWDLxkXIW4lj8DQPnCjePgGu+P4m9GAo3jFZtaY3g0qMj+Dj+t0eMcfFSzeQWLhM5vSwEIgSo5OHbyhSw0KXyUbgpwrLa9dPj+ltCVIlcNnFYf0k+hT/Sr5YkbhoV09CWBpfcFw+8PZgOU5sV8s0X9Y60ZHX40x6kL8PQWelmiOv07c16lxTZlNdVBhq+qgcvKw+lSkAvxJ3pZl2NL+g72w7HOxr29zkoKm7c52PgrlDTmTIAuCJd1pCG0D4LK5vKWjUNkbzYCFpxS8LMCRZVkpPv0mp9rZh8KxvSthhgWD5Gt+WT/OBB7j78V6qBaCB4UGPFyFmbVZtH+XDn9qYSTLbmO0ilnF++40OqIPkbcN7AjtgBUtWUbdNYCNQevTCnsJd764dLBgV8/8oZiEb1xYPpVZjC
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: helm-secrets-private-keys
      namespace: rackspace-system
