apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd-gateway-route
  namespace: rackspace-system
spec:
  parentRefs:
  - name: rmpk-gateway
    sectionName: argocd-https
    namespace: rackspace-system
  hostnames:
  - "<REPLACME>"
  rules:
    - backendRefs:
      - name: argocd-server
        port: 80