namespace: rackspace-system
helmGlobals:
  chartHome: ../charts/
helmCharts:
- name: gateway-helm
  repo: oci://docker.io/envoyproxy
  version: v0.0.0-latest
  releaseName: eg
  includeCRDs: true
  valuesFile: values.yaml
